# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paypal}
  s.version = "3.0.0pre4"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Tron", "Joseph Halter", "Tobias Luetke"]
  s.date = %q{2010-07-16}
  s.description = %q{Integrate Paypal Express}
  s.email = %q{jonathan@tron.name}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG.md",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "paypal.gemspec",
     "lib/paypal.rb",
     "lib/paypal/certs/paypal_sandbox.pem",
     "lib/paypal/config.rb",
     "lib/paypal/helpers/common.rb",
     "lib/paypal/helpers/rails.rb",
     "lib/paypal/notification.rb",
     "lib/paypal/rails.rb",
     "lib/paypal/version.rb",
     "misc/PayPal - Instant Payment Notification - Technical Overview.pdf",
     "misc/multiruby.sh",
     "misc/paypal.psd",
     "spec/config_spec.rb",
     "spec/fixtures/business_cert.pem",
     "spec/fixtures/business_key.pem",
     "spec/helpers/common_spec.rb",
     "spec/notification_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/JonathanTron/paypal}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Paypal Express Integration}
  s.test_files = [
    "spec/config_spec.rb",
     "spec/helpers/common_spec.rb",
     "spec/notification_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 1.0.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.a"])
      s.add_development_dependency(%q<rcov>, [">= 0.9.8"])
      s.add_development_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<bluecloth>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<rack>, [">= 1.0.0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0.a"])
      s.add_dependency(%q<rcov>, [">= 0.9.8"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<bluecloth>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 1.0.0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0.a"])
    s.add_dependency(%q<rcov>, [">= 0.9.8"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<bluecloth>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end

